whatwg/sg

- IPR Policy.md
- SG Agreement.md
- Workstream Policy.md
These are all issues where the Markdown in question is unfriendly to the HTML-conversion script, or where a link was inadvertently forgotten, leaving brackets in the source. Found by grepping the generated output for "[".
> Editorial: fix a few Markdown errors

- README.md
- code-of-conduct
This makes it consistent with https://wiki.whatwg.org/wiki/Style.
> Editorial: use Oxford comma in Code of Conduct

- Workstream Policy.md
- policy-link-mapping.txt
- Fixes #51
- Also links to the SG repo's LICENSE file as an example
- Updates policy-link-mapping,txt so the link still works on whatwg.org
> Give guidance for LICENSE files in repositories

- code-of-conduct
- working-mode
The main content of this is syncing working-mode and code-of-conduct back from whatwg.org. We accidentally made editorial changes to these documents in the whatwg.org repository, instead of properly making them here and then syncing them over. This will hopefully be solved soon by whatwg/whatwg.org#133. In the meantime, perform this manual sync.
The changes were made in:
* whatwg/whatwg.org@4d34512 (site redesign)
* whatwg/whatwg.org@0b93777 (fixes a link)
> Update whatwg.org docs

- IPR Policy.md
This fixes a case where section 2.8.1 says "of Subsection 2.7.3., below.", but 2.7.3 doesn't exist (and would be above if it did), and the link is correctly to 2.8.3, so I think the text should also say 2.8.3.
> Fix description of later section that doesn't match its actual number

- README.md
Hopefully this reduces the risk of folks sharing different URLs.
This also fixes a number of links that were broken due to renaming IDs.
Fixes #64.
> Link to whatwg.org policy documents

- README.md
Google and Microsoft have both had (or are having) transitions of their SG representatives.  This should be documented here.  I'm requesting review from both old and new SG representatives in both cases.
The list *appears* to be alphabetical by whole name (in practice, by first name).  At least, I think that looks like the logic.
> Update SG representatives for Google and Microsoft.

- Code of Conduct.md
This results in erroneous HTML as discovered at https://github.com/whatwg/whatwg.org/pull/255. When displayed on GitHub the email will still present as a link.
> Editorial: do not use link syntax for email

- IPR Policy.md
Hopefully helps with https://github.com/whatwg/whatwg.org/pull/255.
> Editorial: add newlines to improve conversion to HTML

- Code of Conduct.md
I missed in 81d78b807ddb3d23e8cdafd10094ade0f2c0e0b4 that angle brackets are important. SG Policy.md does this correctly. (GitHub does not care, but CommonMark does.)
> Editorial: CommonMark syntax for email address

- .github/workflows/dispatch.yml
Fixes https://github.com/whatwg/sg/issues/110.
> Trigger deploy of whatwg.org on changes

- .github/workflows/dispatch.yml
- .github/workflows/test.yml
- README.md
- policy-link-mapping.txt
Helps with https://github.com/whatwg/meta/issues/174.
> Default branch rename

- db.json
- db.py
This can be used to find the Twitter account of a standard, which is useful for https://github.com/whatwg/meta/issues/109. We can also use it to advertise these accounts, e.g., on spec.whatwg.org.
> db.json: add twitter to standards

- Workstream Policy.md
They are somewhat vague and duplicative of other requirements.
Closes #168.
I plan to merge this with 1 approving review as we already discussed and agreed upon this.
> Require less from Workstream proposals

- db.json
Closes https://github.com/whatwg/sg/issues/140.
> Add the Test Utils Workstream and Standard

- db.json
- db.py
See https://github.com/whatwg/meta/issues/202.
Also fixes db.py to work on environments where the default encoding is not UTF-8, i.e., on Windows.
I chose 3,9 as the review draft schedule as that seems to be the new time we're lumping things at (for Web IDL and TestUtils).
Do not merge quite yet; the DNS propagation seems to be still in progress, so https://websockets.spec.whatwg.org does not work at the moment.
Also remember we need to re-deploy participate.whatwg.org manually per https://github.com/whatwg/sg/issues/171.
> Add WebSockets Standard

- .github/workflows/dispatch.yml
Closes https://github.com/whatwg/sg/issues/171.
> Trigger participate.whatwg.org deploy on changes

- IPR Policy.md
And reference them from rather than referencing the 5.2 and 5.3 sections that deal with time periods.
(This intentionally does not change the references in 2.8.2 that are about the time periods.)
Closes #95.
> Change Patent Licensing Obligation subtypes into definitions

- Workstream Policy.md
Fixes #40
Since translations are generally produced independently, I framed this as a recommendation rather than a requirememt. Translators can technically do whatever they want as long as they follow the
requirements of the license.
> Add advice for copyright notices on translations of Living Standards

- Working Mode.md
The previous text implied that non-normative changes were the same as editorial changes. At least using the definition of "editorial" in https://github.com/whatwg/meta/blob/main/COMMITTING.md#title-prefixes, this is not correct; non-normative changes are a superset of editorial changes.
Kudos to @jeremyroman for pointing this out.
> Clarify and exemplify non-normative changes

- Stages.md
remove extraneous parenthesis from markdown syntax left in HTML links
> Fix html links

- Stages.md
IDs for stages in the table to enable to direct linking to a specific stage
> frag ids for stages

- db.json
Corresponding to https://github.com/whatwg/sg/issues/231.
> Add Compression Standard to db.json

- Workstream Policy.md
Insert agreed and approved "Trivial Changes" definition from https://github.com/whatwg/sg/issues/63#issuecomment-1387475350 into our Workstream Policy per agreement in https://github.com/whatwg/sg/issues/63#issuecomment-1402482837
> add Trivial Changes description to Workstream Policy

- Stages.md
This includes stage 4 issues and closed issues. Since there aren't too many, it seems worth biasing toward showing the historical record, instead of preserving space for only the active proposals.
> Link to more stages issues
