policy-link-mapping.txt

Add link mapping file for HTML conversion script

---

IPR Policy.md
Principles.md
SG Agreement.md
SG Policy.md
Workstream Policy.md

Make titles consistently start with "WHATWG" (no "The")

---

Workstream Policy.md

Make clear that no separate copyright notice is required for supporting resources

---

Workstreams.md

Bocoup is a participant: https://github.com/whatwg/participant-data/blob/3bbc427c208bf3ca324212ed7b475c3448c26f52/entities.json#L176-L201

Remove notice about "pending completion of the CWA" for Simon

---

working-mode

Part of whatwg/meta#84.
@whatwg/editors thoughts? Does this seem reasonable?
<del>(This is on top of #71. Please only review the last commit. I will rebase when this is merged.)</del><ins>(This has been rebased and is now a single commit.)</ins>

Add "Anchor permanence" policy

---

Policies.md
policy-link-mapping.txt

Maintain whatwg.org/policies here

---

Code of Conduct.md
IPR Policy.md
Policies.md
Principles.md
SG Agreement.md
SG Policy.md
Workstream Policy.md
Workstreams.md

Helps with #78. Depends on https://github.com/whatwg/whatwg.org/pull/295 and https://github.com/whatwg/whatwg.org/pull/240 will make it even better.

Add <footer> markup

---

Workstream Policy.md

Working Policy: document RD publication exception

---

Working Mode.md

Working Mode: clarify that major changes warrant additional time

---

Working Mode.md

Expand on “don’t write fiction”

---

db.json
db.py

This helps with automating aspects of Review Draft publication.
Closes #127.

db.json: give standards a review_draft_schedule

---

IPR Policy.md

Closes https://github.com/whatwg/sg/issues/67.

Define (Work in the) Field of Web Technologies

---

Code of Conduct.md
IPR Policy.md
LICENSE
Policies.md
Principles.md
Privacy Policy.md
SG Agreement.md
SG Policy.md
Working Mode.md
Workstream Policy.md

Closes https://github.com/whatwg/sg/issues/102.

Remove year from example LICENSE file

---

db.json

Follows https://github.com/whatwg/streams/pull/1144.
Don't merge until https://github.com/whatwg/streams/pull/1144 is merged; in particular @MattiasBuelens may or may not want to expose his email.

Update Streams authors

---

SG Policy.md

Also correct one instance of SG Members that should say SG Representatives.
Closes #54.

Document that the SG consults with legal representatives

---

Privacy Policy.md

Reword automated decision-making

---

db.json

See https://www.w3.org/2021/06/WHATWG-W3C-MOU_2021_update.html for context.

Add the Web IDL Workstream and Standard

---

Working Mode.md

Rough-draft of a new section describing the WHATWG approach to meetings.
I took this as an action from the 2021-11-03 SG meeting.

Add section on Meetings to Work Mode

---

Working Mode.md

Suggested by @TimothyGu:
https://github.com/whatwg/sg/pull/177#pullrequestreview-801737561

Fix "liase" typo in Working Mode

---

db.json

Closes #176.
---
I still need to create the necessary repository for this, but I thought I would put this up for review to allow that to happen in parallel.
cc @mkruisselbrink

Add File System Standard

---

README.md

Add
* cwilso
* tantek
Drop
* foolip
* annevk

Update SG representative list

---

SG Policy.md

Document policy change policy

---

Invited Individual Policy.md
Policies.md
policy-link-mapping.txt

Goes with https://github.com/whatwg/participate.whatwg.org/pull/170.

Define Invited Individual term and rename policy

---

Working Mode.md

Acknowledge at least one Workstream has a regular meeting

---

README.md

I notified the W3C in https://github.com/w3c/whatwg-coord/issues/19. I also updated the email address and the GitHub Team.

Update SG representative for Apple

---

README.md

As per https://github.com/whatwg/sg/pull/202#discussion_r1044307051.

Editorial: add parenthesis

---

db.json

Replace @mkruisselbrink with @a-sully as File System editor

---

db.json

See https://github.com/whatwg/sg/issues/215.

Add the URL Pattern Standard

---

Working Mode.md

@jyasskin reported a link break.

Capitalization of stages

---

db.json

Thanks @domfarolino for all your contributions over the years, and your willingness to step up and help out with editing duties!

Add Dominic Farolino as a HTML Standard author

---

README.md
SG Agreement.md

Define Alternate Steering Group Representative
